[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.ollama"

[deploy]
startCommand = "ollama serve"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "ollama"
